import { useState } from 'react';
import { Modal, Checkbox } from 'antd';

const TermsCheckbox = ({ checked, onChange }) => {
  const [isModalVisible, setIsModalVisible] = useState(false);

  const showModal = () => setIsModalVisible(true);
  const handleClose = () => setIsModalVisible(false);

  return (
    <>
      <Checkbox checked={checked} onChange={onChange}>
        Acepto que he recibido el{' '}
        <span onClick={showModal} style={{ color: 'blue', cursor: 'pointer', textDecoration: 'underline' }}>
          reglamento
        </span>{' '}
        y el directorio de la administración
      </Checkbox>

      <Modal title="Reglamento del Condominio" open={isModalVisible} onCancel={handleClose} footer={null}>
        <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }}>
        {
            `
            REGLAMENTO DE USO DE LA ALBERCA
1.	LA ALBERCA ES PROPIEDAD COLECTIVA. PERTENECE A TODOS LOS CONDÓMINOS DE LA TORRE XIRIS Y POR TANTO SE DEBEN OBSERVAR ESTAS REGLAS:
2.	LOS CONDIMINOS SON RESPONSABLE DEL ADECUADO USO DE LA ALBERCA, POR TANTO SON QUIENES DEBEN RESPONDER POR LAS ACCIONES PERSONALES Y DE SUS FAMILIARES E INVITADOS.
3.	LOS VIGILANTES DEL EDIFICIO SON LOS ENCARGADOS DE VIGILAR EL CUMPLIMIENTO DE ESTAS REGLAS DE USO, ES NECESARIO RESPETARLOS; AGREDIRLOS, INSULTARLOS O AMENAZARLOS POR EXIGIR SU CUMPLIMIENTO IMPLICA CONSECUENCIAS LEGALES.
4.	ESTÁ PROHIBIDO ENTRAR A LA ALBERCA CON BOTELLAS, VASOS O RECIPENTES DE CRISTAL, LATAS, DESECHABLES, SUS RESIDUOS EN EL FONDO DE LA ALBERCA PUEDEN CAUSAR DAÑOS A LOS USUARIOS O AFECTAR LOS FILTROS.
5.	SE PROHIBE HACER FIESTAS EN EL ÁREA DE LA ALBERCA.
6.	NINGÚN OBJETO DE CRISTAL PUEDE ESTAR A UNA DISTANCIA MENOR A UN METRO DEL BORDE DE LA ALBERCA. EN TODA ESA ÁREA SOLO SE PERMITE TENER VASOS DE PLÁSTICO.
7.	NO SE PERMITE ECHAR A LA ALBERCA CORCHOLATAS O CUALQUIER OBJETO, BASURA O RESIDUO.
8.	NO SE PUEDE ENTRAR A LA ALBERCA CON ROPA QUE NO SEA EXCLUSIVAMENTE LA QUE SE USA COMO TRAJE DE BAÑO.
9.	NO SE PUEDEN METER AL AGUA PERROS NI NINGUNA MASCOTA. SI SUCEDE SE COBRARÁ UNA INFRACCIÓN DE $800.00 QUE SE CARGARÁ AL RECIBO DE LA CUOTA MENSUAL.
10.	ESTÁ PROHIBIDO QUE MASCOTAS DEJEN HECES U ORÍN. EL CONDÓMINO PROPIETARIO O SUS FAMILIARES O INVITADOS, DEBEN RECOGER EL EXCREMENTO U ORÍN. DE NO HACERLO SE LE COBRARÁ UNA INFRACCIÓN DE $500.00 POR CONTAMINAR EL ÁREA.
11.	DEBE EVITARSE QUE CUAQUIER PERSONA HAGA SUS NECESIDADES FISIOLÓGICA DENTRO DE LA ALBERCA. SI ESTO SUCEDIERA, SE VACIARÁ LA ALBERCA PARA EVITAR LA CONTAMINACIÓN Y SU SERÁ COBRADO AL CONDÓMINO CUYA FAMILIA O INVITADOS REALICEN TAL CONDUCTA, VOLUNTARIA O INVOLUNTARIAMENTE.
12.	LOS CÓNDOMINOS SON RESPONSABLES EN LO PERSONAL Y DE LA CONDUCTA DE SUS INVITADOS, POR LO QUE DEBEN RESPONDER POR LA FALTA DE CUMPLIMIENTO DE ESTE REGLAMENTO, ASÍ COMO LOS DAÑOS QUE SE OCASIONEN A LAS INSTALACIONES, MOBILIARIO O PERSONAS; ADEMÁS DE REPARAR LOS DAÑOS EL CONDÓMINO ESTARÁ OBLIGADO A CUBRIR UNA MULTA DE $1000.OO QUE SE CARGARÁ A LA CUOTA MENSUAL. 
13.	SE PROHIBE CONSUMIR DROGAS O SUSTANCIAS PROHIBIDAS EN CUALQUIER ÁREA COMÚN, INCLUÍDA LA ALBERCA POR ESTAR PROHIBIDO POR LA LEY.
14.	SE PROHIBE CUALQUIER TIPO DE ACTITUD O COMPORTAMIENTO SEXUAL EN ÁREAS COMUNES, INCLUIDA EL ÁREA DE LA ALBERCA.
15.	LOS CONDÓMINOS Y SUS INVITADOS ESTÁN OBLIGADOS A LLEVAR SU PROPIA BASURA O DESECHOS, AL CUARTO DE BASURA DEL NIVEL E2, PARA EVTAR CONTAMINACIÓN.
16.	LA MÚSICA QUE LLEVE ALGÚN CODÓMINO AL ÁREA DE LA ALBERCA DEBE MANTENER EL VOLUMEN QUE PERMITA ABARCAR SÓLO EL ÁREA DONDE ESTÁ, PARA PERMITIR QUE OTRO CONDÓMINO PUEDA PONER SU PROPIA MÚSICA EN OTRA ÁREA; LA MÚSICA EN EL ÁREA DE LA ALBERCA SÓLO SE PERMITE HASTA LAS 21:00 HORAS.
17.	QUEDA PROHIBIDO APARTAR EL MOBILIARIO SIN ESTAR PRESENTE EN EL ÁREA  LA ALBERCA.
18.	EL USO DE LOS ASADORES DE LA ALBERCA ESTÁ CONDICIONADO A SOLICITAR EL PERMISO POR ESCRITO CORRESPONDIENTE A LA ADMINSTRACIÓN, A EFECTO DE EVITAR EVENTOS SIMULTÁNEOS.
19.	LA ADMINISTRACIÓN NO ES RESPONSABLE DE ACCIDENTES NI INCIDENTES ORIGINADOS POR LA FALTA DE SUPERVISIÓN DE MENORES DE EDAD. 
20.	LA FALTA DE OBSERVACIÓN REITERADA DE ESTE REGLAMENTO, ASÍ COMO INCURRIR EN CONDUCTAS QUE PONGAN EN RIESGO LA SALUD O LA VIDA DE OTRAS PERSONA ES MOTIVO PARA SER SUSPENDIDO DEL DERECHO DE USO DEL ÁREA DE LA ALBERCA POR EL TIEMPO QUE LA ASOCIACIÓN DE CÓNDOMINOS LO ESTIME NECESARIO  

ASOCIACIÓN CONDÓMINOS XIRIS A.C.

            `
        }
        </pre>
      </Modal>
    </>
  );
};

export default TermsCheckbox;
